type User @table {
  displayName: String!
  email: String
  photoUrl: String
  createdAt: Timestamp!
}

type Movie @table {
  title: String!
  year: Int!
  summary: String
  genres: [String]
  runtime: Int
  createdAt: Timestamp!
}

type Watch @table {
  user: User!
  movie: Movie!
  watchDate: Date!
  location: String
  createdAt: Timestamp!
}

type Review @table {
  movie: Movie!
  user: User!
  watch: Watch!
  rating: Int!
  text: String
  isPublic: Boolean!
  shareLink: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type MovieList @table {
  user: User!
  name: String!
  description: String
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type MovieListEntry @table {
  movieList: MovieList!
  movie: Movie!
  position: Int!
  note: String
}